version: '3.9'

services:
  chadloader:
    build: .
    container_name: chadloader
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - ENV=production
